<?php
namespace App\Http\Controller;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Routing\Controller;


/**
 * @LandingController
 *
 * @package App\Http\Controller
 *
 * <Generated By Laventure 09/04/2022 07:37:40>
*/
class LandingController extends Controller
{

        /**
         * @var string
        */
        protected $layout = 'layouts/default';


         
        /**
         * @Route(methods="GET|POST", path="/", name="home")
         *
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
              return $this->render('landing/index.php');
        }




        /**
         * @Route(methods="GET|POST", path="/contact", name="contact")
         *
         * @param Request $request
         * @return Response
        */
        public function contact(Request $request): Response
        {
            if ($request->isPOST()) {
                dump($request->request->all());
            }

            return $this->render('landing/index.php');
        }
}
